# -*- coding: utf-8 -*-
"""salesPredication3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T1PniDTh3k6HPBMH-E3pMMyFCfev9dU4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('Advertising.csv')

X=df.drop('Sales',axis=1)
y=df['Sales']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size = 0.30, random_state = 0)

from sklearn.linear_model import LinearRegression
Lr= LinearRegression()

Lr.fit(X_train,y_train)

y_pred=Lr.predict(X_test)

y_pred

plt.scatter(y_test,y_pred,c='b')